[build]
  command = "#"
  functions = "functions"
  publish = "build"
[dev]
  functions = "functions"
  publish   = "build"
  # We manually set the framework to static, otherwise Netlify automatically
  # detects NextJS and redirects do not work.
  # Read more: https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  framework = "#static"
[[redirects]]
  from = "/participate-submit"
  to = "/.netlify/functions/handleParticipate"
  status = 200
  force = true
